# Generated by Django 5.0.1 on 2024-01-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviedetails',
            options={'ordering': ('title',), 'verbose_name': 'MovieDetail', 'verbose_name_plural': 'MovieDetails'},
        ),
    ]
