# Generated by Django 5.0.1 on 2024-02-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine_app', '0002_alter_moviedetails_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
