# Generated by Django 5.0.1 on 2024-02-04 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_app', '0003_delete_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=250)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine_app.moviedetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CommentSection',
                'verbose_name_plural': 'CommentSections',
                'ordering': ('user',),
            },
        ),
    ]
